WTF-72 filtering build based on env var

diff --git a/go-common/codebuild/pr-checker.yaml b/go-common/codebuild/pr-checker.yaml
--- a/go-common/codebuild/pr-checker.yaml
+++ b/go-common/codebuild/pr-checker.yaml
@@ -11,24 +11,34 @@ phases:
       - |
         if echo "$CHANGED_FILES" | grep -q "go-common/"; then
           echo "Relevant files have changed. Proceeding with build."
+          export RUN_BUILD=true
         else
           echo "No relevant files changed. Skipping build."
-          exit 0
+          export RUN_BUILD=false
         fi
   build:
     commands:
-      - echo "Running the build as changes are detected in the specified files."
-      - echo build started on `date`
-      # Start the SSH agent
-      - eval $(ssh-agent -s)
-      # Add the SSH key from the environment variable to the agent
-      - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
-      # Add GitHub to known hosts to prevent host key verification failures
-      - mkdir -p ~/.ssh
-      - ssh-keyscan github.com >> ~/.ssh/known_hosts
-      # Force Git to use SSH instead of HTTPS
-      - git config --global url."git@github.com:".insteadOf "https://github.com/"
-      - cd go-common && make ci
+      - |
+        if [ "$RUN_BUILD" = "true" ]; then
+          echo "Running the build as changes are detected in the specified files."
+          echo build started on `date`
+          # Start the SSH agent if SSH_PRIVATE_KEY is set
+          if [ -n "$SSH_PRIVATE_KEY" ]; then
+            eval $(ssh-agent -s)
+            echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
+          else
+            echo "SSH_PRIVATE_KEY is not set. Exiting build."
+            exit 1
+          fi
+          # Add GitHub to known hosts to prevent host key verification failures
+          mkdir -p ~/.ssh
+          ssh-keyscan github.com >> ~/.ssh/known_hosts
+          # Force Git to use SSH instead of HTTPS
+          git config --global url."git@github.com:".insteadOf "https://github.com/"
+          cd go-common && make ci
+        else
+          echo "Skipping build phase as no relevant files were changed."
+        fi
   post_build:
     commands:
       - echo "Build completed."
